server:
  port: 8080

spring:
  application:
    name: Chora_Auth
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/sso_db
    username: admin
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    drop-first: true
  web:
    resources:
      add-mappings: true

auth:
  jwks:
    issuer: https://auth.example.com
    audience:
      - orders-service
      - billing-service
  tokens:
    access-ttl-minutes: 10
    refresh-ttl-days: 14

logging:
  level:
    org.springframework.security: DEBUG
    liquibase: INFO
    org:
      springframework:
        boot:
          autoconfigure:
            liquibase: DEBUG
